Modified erasure so we have enough information to determine whether we need to use scala or java erasure semantics.  This fixes the runtime failure illustrated here:
  % scala29 -e 'java.util.Collections.max(null)'
  java.lang.NoSuchMethodError: java.util.Collections.max(Ljava/util/Collection;)Ljava/lang/Comparable;

Review by odersky.

git-svn-id: https://lampsvn.epfl.ch/svn-repos/scala/scala/trunk@25323 5e8d7ff9-d8ef-0310-90f0-a4852d11357a