Revert "closes #3477. undid part of the fix for #3152 so that all type parameters are reported in error messages about failing type inference"
the idea of mapping type parameter symbols to the corresponding type ref in order to make substitution the identity does not seem to work (I guess that's why they were retracted, which then caused 3152 because that lead to a mismatch between type params and type args)

src/library/scala/collection/immutable/SortedMap.scala:38: error: type mismatch;
  found   : scala.collection.immutable.SortedMap[A,B(in method empty)]
  required: scala.collection.immutable.SortedMap[A,B(in trait SortedMap)]
   override def empty: SortedMap[A, B] = SortedMap.empty
                                                   ^

This reverts commit 29adbf6ed974884a7aff357fe8fc737409e6438e.